# Source: https://github.com/argoproj/argocd-example-apps/tree/master/kustomize-guestbook
namePrefix: kustomize-

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
